[package]
name = "matching"
version = "0.1.0"
authors = ["Daan van Berkel <daan.van.berkel@alliander.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.4.13"